project:
  type: website

website:
  title: "STATGEN_FP"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: implementation.qmd
        text: Implementation
      - href: methods.qmd
        text: Methods
      - href: results.qmd
        text: Results

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
