project:
  type: website

website:
  title: "Collider Bias in Statistical Genetics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: implementation.qmd
        text: Implementation
      - href: limitations.qmd
        text: Limitations
      - href: other_methods.qmd
        text: Other Methods
      - href: sources.qmd
        text: Sources
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
